### ISSUE TITLE
It doesn't work for me with typescript

### ISSUE THREAD

**Issue by bafroc** [louaySleman/react-native-accordion-list-view#2]
Error:
Could not find a declaration file for module 'react-native-accordion-list-view'. 'D:/www/jetbox-rn/node_modules/react-native-accordion-list-view/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-accordion-list-view` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-accordion-list-view';

**Comment by louaySleman** [comment]
We've changed the library code to typescript you can check our latest version `2.0.0`

https://www.npmjs.com/package/react-native-accordion-list-view
