### ISSUE TITLE
How to expand 1st or nth list by default using AccordionList component.

### ISSUE THREAD

**Issue by shaikhkhamroddin** [louaySleman/react-native-accordion-list-view#5]
How to expand 1st or nth list by default using AccordionList component, as AccordionListItem have isOpen flag but I want to use AccordianList.

**Comment by louaySleman** [comment]
Thanks for your comment I'll add this feature in the next release and I'll let you know when it's live

**Comment by louaySleman** [comment]
I'm happy to inform you that in version 2.0.2 of the package, we have introduced a feature that allows you to expand the 1st or nth list by default.
You can achieve this by using the `defaultOpenIndices` prop in the AccordionList component. Simply pass an array of the indices that you want to be opened by default. It's important to note that if the `expandMultiple` prop is set to `false`, this array should contain only one index.
You can check the new version from [here - react-native-accordion-list-view](https://www.npmjs.com/package/react-native-accordion-list-view)
