### ISSUE TITLE
How to get index of item for list item in AccordionList component for customtitle,customicon and customicon.

### ISSUE THREAD

**Issue by shaikhkhamroddin** [louaySleman/react-native-accordion-list-view#6]
I am trying to get index from 
customtitle,customicon and customicon these props for AccordionList , but it only passes item to the render function.

<AccordionList
        {...getTestID('regionlist-container' + item[0])}
        data={regionSortedList}
        customTitle={(regionList, regionIndex) =>
          getCustomTitleRegion(regionList, MULTISELECT_KEYS[2], regionIndex)
        }
        customBody={MobileListView}
        customIcon={() => <Text />}
        containerItemStyle={styles.regionListContainer}
        style={styles.regionListItem}
      />

On above code I am getting regionIndex as undefined.

**Comment by louaySleman** [comment]
Thanks for your comment, I'll add this feature in the next two days stay tuned

**Comment by louaySleman** [comment]
@shaikhkhamroddin  Exciting News! 🚀 In version 2.0.3 of our package, we're thrilled to introduce a fantastic new feature that makes it even easier for you to customize your accordion items. Now, you can effortlessly access the index within the `customTitle`, `customBody`, and `customIcon` functions by default.

Take a look at this example to see how simple it is to use the new `index` parameter:

```jsx
<AccordionList
  data={data}
  customTitle={(item, index) => <Text>{item.title}</Text>}
  customBody={(item, index) => <Text>{item.body}</Text>}
  customIcon={(index) => <AntDesign name={'plus'} />}
  animationDuration={400}
/>
```
This enhancement provides you with more flexibility to tailor your accordion items exactly to your liking. Explore the latest version [here - react-native-accordion-list-view](https://www.npmjs.com/package/react-native-accordion-list-view) and elevate your app's user experience!
