### ISSUE TITLE
Custom color

### ISSUE THREAD

**Issue by Mukhammadjon-Jalolov** [louaySleman/react-native-accordion-list-view#8]
How to set a background color of the Accordion itself? I tried many options but it did not work. 
![Screenshot 2024-10-06 224229](https://github.com/user-attachments/assets/24c2d4c0-212d-4083-8af0-fa76391cf881)
For example in this screenshot, my text color is black and it can be customized.
And with this style I can only set a background color for the view around the text only. Shown in grey in image.

If I add style to the Accordion itself using pressableProps (Yellow background) again it is not being applied to the Accordion, rather its parent view.
```
pressableProps={{
    style: styles.pressableStyle,  // Background color for the Accordion (the part that opens/closes)
  }}
```

How to change the Accordion's background color completely in this case? Like in the second image I attached if possible. Thank you in advance!
![AccordionColored](https://github.com/user-attachments/assets/a1053c4b-fd52-4f80-baa0-f587eea5be01)

**Comment by louaySleman** [comment]
Sorry for the delayed response! I hope this still helps.
The correct way to set the background color for the entire Accordion is by using the `containerItemStyle` prop, not through `pressableProps`.
The `pressableProps.style` only affects the pressable area, while containerItemStyle controls the entire Accordion container's styling. Here's an example:
```
<AccordionList
  containerItemStyle={{
    backgroundColor: 'yellow',  // This will color the whole Accordion
    padding: 0
  }}
  // ... other props
/>
```

You can still customize the pressed state separately using pressableProps if needed:

```
pressableProps={{
  style: ({pressed}) => [{
    padding: '2%',
    backgroundColor: pressed ? 'rgb(210, 230, 255)' : 'transparent'
  }]
}}
```
For a working example, check out this [Expo Snack](https://snack.expo.dev/@louaysleman/custom-color---react-native-accordion-list-view)

Hope this helps clarify the styling approach! Let me know if you need any additional clarification.

@Mukhammadjon-Jalolov
